defaults: &defaults
  plans:
   -
    display: 'Launch'
    name: 'silver'
    price: 50
    credit: 20
   -
    display: 'Growth'
    name: 'gold'
    price: 100
    credit: 50

  subscription_plans:
   -
    name: 'free'
    price: 0
    quota: 3600 # 1.hours
    duration: 30
   -
    name: 'tier1'
    price: 50
    quota: 10800 # 3.hours
    duration: 30
   -
    name: 'tier2'
    price: 150
    quota: 36000 # 10.hours
    duration: 30
   -
    name: 'tier3'
    price: 300
    quota: 108000 # 30.hours
    duration: 30

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
