defaults: &defaults
  plans:
   -
    display: 'Launch'
    name: 'silver'
    price: 50
    credit: 20
   -
    display: 'Growth'
    name: 'gold'
    price: 100
    credit: 50

  subscription_plans:
   -
    display: 'Unlimited'
    name: 'volume'
    price: 200
    credit: unlimited

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
