defaults: &defaults
  plans:
   -
    display: 'A La Carte'
    name: 'one'
    price: 5
    credit: 2
   -
    display: 'Launch'
    name: 'few'
    price: 50
    credit: 40
   -
    display: 'Growth'
    name: 'volume'
    price: 100
    credit: 100

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
