defaults: &defaults
  plans:
   -
    display: 'Launch'
    name: 'few'
    price: 50
    credit: 20
   -
    display: 'Growth'
    name: 'volume'
    price: 100
    credit: 50

development:
  <<: *defaults

test:
  plans:
   -
    display: 'Growth'
    name: 'volume'
    price: 100
    credit: 100

production:
  <<: *defaults
