defaults: &defaults
  plans:
   -
    display: 'Launch'
    name: 'silver'
    price: 50
    credit: 20
   -
    display: 'Growth'
    name: 'gold'
    price: 100
    credit: 50

  # quota is in hours and duration is in days.
  subscription_plans:
   -
    name: 'free'
    price: 0
    quota: 1
    duration: 30
   -
    name: 'tier1'
    price: 50
    quota: 3
    duration: 30
   -
    name: 'tier2'
    price: 150
    quota: 10
    duration: 30
   -
    name: 'tier3'
    price: 300
    quota: 30
    duration: 30

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
