defaults: &defaults 
  plans:
   - 
    name: 'one' 
    price: 5
    credit: 1 
   - 
    name: 'few' 
    price: 50
    credit: 20 
   - 
    name: 'volume' 
    price: 100
    credit: 50 

development: 
  <<: *defaults

test: 
  <<: *defaults

production: 
  <<: *defaults
