defaults: &defaults
  plans:
   -
    display: 'Launch'
    name: 'silver'
    price: 50
    credit: 20
   -
    display: 'Growth'
    name: 'gold'
    price: 100
    credit: 50
   -
    display: 'Unlimited'
    name: 'volume'
    price: 200
    credit: unlimited

development:
  <<: *defaults

test:
  plans:
   -
    display: 'A La Carte'
    name: 'one'
    price: 5
    credit: 1
   -
    display: 'Launch'
    name: 'few'
    price: 50
    credit: 20
   -
    display: 'Unlimited'
    name: 'volume'
    price: 500
    credit: 100

production:
  <<: *defaults
